### ISSUE TITLE
Require legal XML for quest spec and offer a translator.

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#101]
Store final version in full valid HTML/XML and offer a means to translate into that from the existing lightweight version.

**Comment by smartin015** [comment]
See #26 for context

**Comment by toddmedema** [comment]
Idea: we could use Gulp to watch quest files for changes, and run them through the translator on save, kind of like a reverse minifier

**Comment by toddmedema** [comment]
Update: no need for a translator now, QDL is now legal XML from the get-go
