### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#107]
We're getting several deprecation warnings in console. One in particular is a bit concerning:

keyframe-effect-constructor.js:128
"Specifying animation easing as a function is deprecated and all support will be removed in M54, around October 2016, at which point this will throw a TypeError. This warning may have been triggered by the Web Animations or Polymer polyfills. See http://crbug.com/601672 for details."

**Comment by toddmedema** [comment]
Closing; we're no longer getting this error. Also, we totally rebuilt the app in React
