### ISSUE TITLE
Create polite user agent check / notification

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-app#13]
If users are opening the app in not-Chrome / not a recent version of Chrome, the homescreen should include a polite alert along the lines of "For the best experience, we recommend running Expedition in the latest version of Chrome: <app store link"

Potential User Agent check: http://stackoverflow.com/a/27022597
```js
var v = navigator.userAgent.match(/Chrome\/(\S+)/);
var res = v ? v[1] : 'Not a Chrome';
```

We could hard-code the check to look for anything v48 or above (note that currently `var res = "50.0.2661.75"` on my desktop)

**Comment by wls** [comment]
Is there a reason to force users to Chrome instead of making the code work with other browsers?

**Comment by toddmedema** [comment]
@wls main reason is limited bandwidth. We could either spend many hours trying to get it to work with Firefox, Safari, old Android stock browsers, Opera and Internet Explorer, or we could spend that time building new features and fixing big bugs. We want to add support for other browsers eventually, it's just a lower priority :)

**Comment by wls** [comment]
I understand where you're coming from, and I'd hope that the _higher_ priority would be the mobile platform.

My understanding, however, is that the libraries being used are supposed to insulate from browser differences, so I'm curious what's browser-speicific.

Historically, telling people they need to use Internet Explorer to view this page, and Opera to view that page, and Chrome to do such-and-such game doesn't fair well. The _long-term_ expectation (which takes into account the priorities) is that HTML5 / CSS3 / JavaScript should work on all browsers.  As long as the design hasn't blocked outside contributors for addressing those issues, things should be good.

**Comment by toddmedema** [comment]
That's true. Going to close / de-prioritize this entirely so that we can focus on fixing bugs on other browsers as people point them out.
