### ISSUE TITLE
Debounce / bugfix touch events

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-app#136]
For example double clicking / tapping buttons triggers the page flip animation (to the same next page) twice

Also, on the multitouch cards like the splash screen, if you hold your finger down in the spot that a button appears on the next card and wait a moment before picking up your finger, it'll auto-click that button

Note: e.preventDefault() didn't fix it. Seems like there might be a whole separate touch / click gesture being fired if you hold your finger down for long enough after a page transition.

**Comment by toddmedema** [comment]
Note: seems like buttons are getting triggered on mouse up / touch end events, which can lead to some odd quirks as well, such as releasing a finger from a multitouch page then accidentally triggering a button on the next page

**Comment by toddmedema** [comment]
Perhaps it's that touch events need to prevent default / return false?

**Comment by toddmedema** [comment]
Related recent bugfix: https://github.com/Fabricate-IO/expedition-app/commit/6e9419c424cd642c94c2052adf2ad947c229c133

**Comment by smartin015** [comment]
Specifically for the initial multitouch check on the splash page, we could be dispatching multiple actions based on user touch events (bug in the multitouch checker?)
