### ISSUE TITLE
Tutorial quest

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-app#175]
@smartin015 Got feedback (aka a 1 star review on the app :( ) because the rules say to "see the tutorial in the app", but there's no tutorial anywhere to be seen!

So, wrote a nice, quick, single-combat quest that we can review. Then, was thinking we can call it tutorial and put it at the top of the quest list.

Was also thinking it'd be cool if that quest always / automatically played at tutorial level difficulty, though don't know how easy that'd be / if there are any gotchas (ie going back, etc)

**Comment by toddmedema** [comment]
Quest published to the app (temporarily / for testing); also visible in Drive/Fabricate/Expedition/Quests/`learning to adventure`

**Comment by smartin015** [comment]
LGTM

**Comment by toddmedema** [comment]
Closed by https://github.com/Fabricate-IO/expedition-app/commit/d9e20ba6c16adefc9215ab7d3cb60913cba28586 and https://github.com/Fabricate-IO/expedition-app/commit/e26e1b6a1a5485220bd1a8c911c8e470b2c37d2d
