### ISSUE TITLE
Use unpublished quest

### ISSUE THREAD

**Issue by skeetermurphy** [Fabricate-IO/expedition-app#177]
It would be nice to be able to playtest a quest without it being published for everyone to see.

Could the app access a quest file in the users Google Drive?

**Comment by toddmedema** [comment]
@skeetermurphy Good call! Moved this to the Quest Creator repo since it's mainly on the Creator side, I'd encourage you to follow the issue there so you can stay up to date and add your feedback :) https://github.com/Fabricate-IO/expedition-quest-creator/issues/148
