### ISSUE TITLE
Satyr tier not correctly recognized

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#196]
During a recent playthrough, a Satyr was listed as Tier I when it's in fact Tier III.

**Comment by toddmedema** [comment]
@smartin015 I believe that's a typo in the quest, they spelled satyr wrong (related: we should throw a warning in the QC when combat has an unrecognized enemy listed)

**Comment by smartin015** [comment]
I'm not so sure. IIRC the spelling was correct... this could be a capitalization or padding issue.

**Comment by toddmedema** [comment]
Shouldn't be capitalization (unless you were running an old version of the app) - do you remember which quest it was so that we can debug?

**Comment by toddmedema** [comment]
Just confirmed locally, Satyr is recognized as tier 3. Betting it was a typo. Closing for now, we can re-open if needed
