### ISSUE TITLE
Tablet UI bugfix

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#198]
We should have icon size scale with screen real estate - currently the icons don't scale for tablet-sized devices.

Also, checkmarks in settings (and possibly also <>'s in player count + setting + combat screens)
->> https://github.com/Fabricate-IO/expedition-app/issues/118

**Comment by toddmedema** [comment]
Split out landscape support here so that this can focus on large screen icon sizing bugfix https://github.com/Fabricate-IO/expedition-app/issues/208

**Comment by toddmedema** [comment]
Added issue to material UI icons: https://github.com/callemall/material-ui/issues/6123

**Comment by toddmedema** [comment]
Update: looks like it should be possible: https://github.com/callemall/material-ui/issues/6123#issuecomment-279384178

Try again with this documentation: http://www.material-ui.com/#/customization/styles
