### ISSUE TITLE
Speeding up combat app flow

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-app#207]
@smartin015 
- show adventurer and enemy damage in the same page?
  - only when help off? Question: how many people turn help off? Enough to cater to them?
- not need to zero tier / adventurer number to win / lose?

**Comment by smartin015** [comment]
We could try enabling the buttons and see if people get confused. Maybe we un-disable the "end encounter" buttons and force the tier to zero before navigating to the next card.

Grouping damage also makes sense for retroactive cards, although UI might get cluttered.
