### ISSUE TITLE
Feedback scrolling on Android

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-app#213]
Bug: users can type an unlimited amount, but eventually gets hidden behind / below the keyboard. They should continue to be able to provide extensive feedback, but also see what they're typing

Limit max text area size so that it fits in one screen (8 rows?), but user can still scroll if they type more

onFocus on text area, scroll the specific card (may need to add id) to the scroll position of the text input

![screenshot_2017-02-09-07-28-58-41](https://cloud.githubusercontent.com/assets/775657/22795973/a9fd93ae-eec6-11e6-8576-cb91b26d5fdf.png)

**Comment by smartin015** [comment]
Addendum: we should move the actual feedback body as close to the start of
the email as possible (before metrics and such) so email previews pick up
the user comments.

**Comment by toddmedema** [comment]
@smartin015 moved feedback closer to the top here: https://github.com/Fabricate-IO/expedition-quest-creator/pull/180
