### ISSUE TITLE
App feedback is returning "vundefined" for iOS

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#235]

**Comment by toddmedema** [comment]
As expected, app hasn't been re-deployed since the PR that added that - https://github.com/Fabricate-IO/expedition-app/commit/1f07db4262b4b4ca26cf0677ec1b6d7cb461ca6a

Waiting on a review of this PR, then I'll roll out: https://github.com/Fabricate-IO/expedition-app/pull/232
