### ISSUE TITLE
Specific rules for single-player game

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#56]
- single player mode is much different than 6 players with 5 people dead. We want the former to be possible, but we don't want the latter to drag on. Perhaps solo mode should be a separate option? 
- not all adventurers are combat ready. Ie a 100% musician doesn't stand a chance. Perhaps we should add a rule about getting to draw 8 abilities from whatever deck you want during solo mode?

**Comment by toddmedema** [comment]
Closing, duplicate of https://github.com/Fabricate-IO/expedition-app/issues/66
