### ISSUE TITLE
Multitouch checker

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#60]
The first time (the app is run? multitouch is selected? whenever multitouch storage count is missing?) on a new device, work with the user to check how many touch points the device supports. Have them put all 10 fingers on the screen, make sure none of the circles are overlapping / fingers aren't too close, and give them a timer to get all their fingers positioned. Then, show them their max touches and save it to the device / storage.

This is now higher priority, apparently the iPhone 6 only supports 5-finger multitouch so a lot of people are going to start running into this issue now that we have an official iOS app.

**Comment by toddmedema** [comment]
Closing now that we have the Chwazi-style player number select.

Only other thought (we can re-open if needed) would be to flash the number of adventurers selected as a final confirmation
