### ISSUE TITLE
Add "Rate the app" to hamburger dropdown, links to OS-appropriate app store

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#61]
Should go above Feedback button (when shown)
Android: https://play.google.com/store/apps/details?id=io.fabricate.expedition
iOS: https://itunes.apple.com/us/app/expedition-roleplaying-card/id1085063478?ls=1&mt=8
Web... don't show if they're running the web app.

Also, "Feedback" -> "Send Feedback"

**Comment by toddmedema** [comment]
Closed by https://github.com/Fabricate-IO/expedition-app/pull/171
