### ISSUE TITLE
Minor TYPO on physical CARD (Rogue) -- PDF needs updating

### ISSUE THREAD

**Issue by wls** [Fabricate-IO/expedition-app#64]
Simple grammatical error on the Rogue card that should be addressed before actual printing:

```
- "All Adventurer with at least 1 look take 2 melee damage."
+ "All Adventurers with at least 1 look take 2 melee damage." 
```

Adventurers should be plural (as it is with the Archer card).  

The PDF needs updating.

**Comment by toddmedema** [comment]
Great catch! Opened an issue in the expedition-cards repo here: https://github.com/Fabricate-IO/expedition-cards/issues/4
