### ISSUE TITLE
Balance the game for different numbers of players

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#65]
Blocked by #69 

Factors to consider:
- loot (the way we do it now, fixed loot pile, actually works well)
- level scaling (ie that larger parties become stronger faster)
- that larger parties have more support abilities, and support abilities are also more powerful
- that being said, giving out the same amount of loot for large and small parties isn't a great UX - small parties would get overwhelmed with loot, large parties not all players get loot

Perhaps take the current damage output as being considered well-balanced for 4 players and divide and multiply from there. I suspect that damage won't need to scale dramatically for varied #'s of players - I would propose:
1 - 0.25 (though this might end up being a special case anyway)
2 - 0.5
3 - 0.75
4 - 1
5 - 1.25
6 - 1.5 (basically forcing at least one person to always be support - might also need to reduce the potency of support in large parties, ie not "enemies deal no damage" but "enemies deal 4 less damage" so that damage multiplier still has an effect)

For actually dealing the damage, rounding is going to be a problem (2/.25 = .5, which will always round to 1, instead of averaging to .5). As such, we can use the fraction as the probability of Math.floor vs Math.ceil. (ie .4 has a 40% chance of ceil, 60% chance of floor)

**Comment by smartin015** [comment]
Heuristic: 
Tier 6 is a boss-level encounter. 
Tier 3-4 is a normal sort of encounter. 
Tier 1-2 is super easy.

This should be done _after_ we change the game mode to a more stepwise accrual (stochastically generate damage for the whole round, plus an extra amount if they're over some default time).

**Comment by toddmedema** [comment]
Unassigning myself from this for now / assigning myself to https://github.com/Fabricate-IO/expedition-app/issues/69 since it's blocked by that

**Comment by toddmedema** [comment]
Note that, when we Rebalance combat, we should also clearly document it, since combat balance will be very important to users designing their own cards - https://github.com/Fabricate-IO/expedition-quest-creator/issues/82#issuecomment-267098997
