### ISSUE TITLE
Quest UI: display instruction blocks differently

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-app#68]
Instruction blocks in quests should stand out from standard `<p>` tags so that it's clearer to users that it's an aside / out of character

**Comment by smartin015** [comment]
In the simple syntax, we shouldn't even need <p> tags... they're an unnecessary artifact of html/xml.

**Comment by wls** [comment]
True  ...although...  two points:

1. The more structure you provide to the language, the more that tools can generate and enforce it.
2. It's easier to educate new users on how you'd like to see something done in the long run, than to remove a "feature" in the future, potentially breaking a lot of existing quests and pissing people off.

Put another way, _right now_ the level of impedance for adopting a `<p> ... </p>` notation is very low, and the benefits are fairly high.
