### ISSUE TITLE
Quest icon injection

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-app#71]
Injecting .SVG content would be awesome. The system could be reused for sound effects (thanks wls@ for the suggestion!)

Possibly bring in Rpg-Awesome or rpg-icon-font icon libraries, but definitely include the Expedition icon set so players do thematically consistent icon injection.

**Comment by toddmedema** [comment]
Also see https://github.com/Fabricate-IO/expedition-app/issues/99

**Comment by toddmedema** [comment]
Also see https://github.com/Fabricate-IO/expedition-quest-creator/issues/46

**Comment by toddmedema** [comment]
Closing now that we have an expanded icon set; can re-open if / when we want more icons
