### ISSUE TITLE
Implement href for expedition-button

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-app#73]
Exhibits itself as quest Tester "Learn More" links broken

Try it out on the beta website or local dev, looks like external links (specifically in the quest tester) don't work when part of the expedition-button element:
```
<expedition-button target="_blank" href="../quests/oust_albanus.txt">Example Quest</expedition-button>
```
Which makes sense, since it's not an `<a>`. But we can manually add support for it.

Should also automatically resolve https://github.com/Fabricate-IO/expedition-app/issues/37

**Comment by smartin015** [comment]
Sounds like we need to implement href for expedition-button :-\
