### ISSUE TITLE
Future idea: voiceover recordings for quests

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-app#78]
In-app purchase of voiceovers for core quests for parties that want a more hands-off experience. Would also be a neat opportunity to incorporate sound effects and music into quests. Suggested by John Hildebrand.

**Comment by smartin015** [comment]
Seems pretty cool - but voice data is large, so we'll either make the app massive or require heavy downloads for VO quests.

**Comment by toddmedema** [comment]
Yep. It'd be a pretty extensive feature that would include an in-app marketplace (we could potential even allow others to sell voiceovers for their quests as a way to monetize them / get more interest in quest creation), plus download management (ie ability to download specific quests / vo's, and manage / remove them to clear up space) 

So,  a big hairy feature :-)

**Comment by toddmedema** [comment]
Closing for now, many more pressing issues
