### ISSUE TITLE
Add Firebase support 

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-app#79]
[x] add plugin to app, send a few analytics events, see what information we get by default
  - looks like iOS vs Android, basic demographic info

[x] add events for quest starts
[x] add events for combat starts and finishes (tier, number of adventurers, difficulty, win v lose, total combat time)
[ ] make sure the events show up in the [Firebase console](https://console.firebase.google.com/project/expedition-quest-ide/overview) as expected
[ ] deploy!

**Comment by smartin015** [comment]
110% agree with this - monitoring is the future!
